namespace Bermuda.ExpressionGeneration
{
    public enum ModifierTypes
    {
        Equals,
        LessThan,
        GreaterThan,
        Like,
        Colon,
        Contains,
        InRange,
        In,
        Multiply,
        Divide,
        Add,
        Subtract,
        Ternary,
        BitXor,
        BitOr,
        And,
        Plus,
        Minus,
        NullCoalesce,
        Or,
        BitAnd,
        NotEquals,
        Modulus,
        LessThanOrEqual,
        GreaterThanOrEqual
    }
}
