/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;

namespace Bermuda.Core.Thrift
{

  [Serializable]
  public partial class ThriftMentionChunk : TBase
  {
    private List<ThriftMention> _Mentions;

    public List<ThriftMention> Mentions
    {
      get
      {
        return _Mentions;
      }
      set
      {
        __isset.Mentions = true;
        this._Mentions = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool Mentions;
    }

    public ThriftMentionChunk() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Mentions = new List<ThriftMention>();
                TList _list4 = iprot.ReadListBegin();
                for( int _i5 = 0; _i5 < _list4.Count; ++_i5)
                {
                  ThriftMention _elem6 = new ThriftMention();
                  _elem6 = new ThriftMention();
                  _elem6.Read(iprot);
                  Mentions.Add(_elem6);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ThriftMentionChunk");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Mentions != null && __isset.Mentions) {
        field.Name = "Mentions";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Mentions.Count));
          foreach (ThriftMention _iter7 in Mentions)
          {
            _iter7.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ThriftMentionChunk(");
      sb.Append("Mentions: ");
      sb.Append(Mentions);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
