/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;

namespace Bermuda.Core.Thrift
{

  [Serializable]
  public partial class ThriftDatapointChunk : TBase
  {
    private List<ThriftDatapoint> _Datapoints;

    public List<ThriftDatapoint> Datapoints
    {
      get
      {
        return _Datapoints;
      }
      set
      {
        __isset.Datapoints = true;
        this._Datapoints = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool Datapoints;
    }

    public ThriftDatapointChunk() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Datapoints = new List<ThriftDatapoint>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  ThriftDatapoint _elem2 = new ThriftDatapoint();
                  _elem2 = new ThriftDatapoint();
                  _elem2.Read(iprot);
                  Datapoints.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ThriftDatapointChunk");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Datapoints != null && __isset.Datapoints) {
        field.Name = "Datapoints";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Datapoints.Count));
          foreach (ThriftDatapoint _iter3 in Datapoints)
          {
            _iter3.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ThriftDatapointChunk(");
      sb.Append("Datapoints: ");
      sb.Append(Datapoints);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
